version: '2'
services:
  # Dependencies if any


  # FooApp Application
  application:
    #cannot be build for it to work
    image: "gcr.io/${PROJECT_ID}/fooapp:${SHORT_SHA}"
    #application name is very importante for the test
    container_name: application
    networks:
      - cloudbuild
    ports:
      - "8080:8080"
    environment:
      - "SERVER_PORT:8080"

# Connect to the existing cloudbuild network
networks:
  cloudbuild:
    external: true