{{ if .Values.blue.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fooapp-blue
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: fooapp
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: fooapp
        release: {{ .Release.Name }}
        slot: blue
    spec:
      containers:
        - name: fooapp-blue
          image: gcr.io/{{ .Values.projectId }}/fooapp:{{ .Values.blue.version }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
{{ end }}