#Build the application and the package it a docker iamge
steps:

#Ensure tests and coverage on every commit
- name: 'gcr.io/cloud-builders/mvn:3.5.0-jdk-8'
  args: ['verify', 'package', '-q']
  dir: 'fooapp/app'

#Run the github a build check
- name: 'gcr.io/cloud-builders/curl'
  args: ['-u', 'rsdomingues:492e88706ac0a93eb8a6edff62be8deadcd6a956', '-X', 'POST', '-d', '{"state": "success","target_url": "https://console.cloud.google.com/cloud-build/builds/83c6f197-bb0e-4005-8369-bb3cb0231d16","description": "The build succeeded!","context": "continuous-integration/cloudbuild"}', 'https://api.github.com/repos/rsdomingues/cloud_blueprint/statuses/54de2b2e94cf06e2d30f2f55428a896f607576da']
  dir:

#For easy filter
tags:
  - "onCommitBuild"