#Build the application and the package it a docker iamge
steps:

#Ensure tests and coverage on every commit
- name: 'gcr.io/cloud-builders/mvn:3.5.0-jdk-8'
  args: ['verify', 'package', '-q']
  dir: 'fooapp/app'

#Run the github a build check
- name: 'gcr.io/cloud-builders/curl'
  args: ['-u', 'rsdomingues:$_GITHUB_TOKEN', '-X', 'POST', '-d', '{"state": "success","target_url": "https://console.cloud.google.com/cloud-build/builds/$BUILD_ID","description": "The build succeeded!","context": "continuous-integration/cloudbuild"}', 'https://api.github.com/repos/rsdomingues/cloud_blueprint/statuses/$COMMIT_SHA']
  dir:

#For easy filter
tags:
  - "onCommitBuild"